-- 23. DISTRICTS — cobertura nacional completa (194 provincias / 1833 distritos)
-- Complementa el seed original (solo 6 ciudades / 46 distritos) con todas las
-- provincias del Perú, para que cualquier profesor pueda registrar su
-- ciudad/distrito real. Fuente: dataset público UBIGEO (INEI-derivado,
-- github.com/joseluisq/ubigeos-peru, licencia libre). Se corrigieron a mano
-- las tildes de Lima, Arequipa, Cusco, Trujillo, Piura, Chiclayo y Callao
-- (donde hoy se concentran las clases); el resto del país viene tal cual
-- de la fuente pública — puede faltar alguna tilde en distritos remotos,
-- revisar si se detecta algo antes de confiar 100% en el dato.
--
-- ON CONFLICT DO NOTHING: la tabla ya tiene UNIQUE(name, city) desde la
-- migración 02, así que las 46 filas ya sembradas (Lima/Arequipa/Cusco/
-- Trujillo/Piura/Chiclayo) se preservan intactas con sus IDs originales —
-- esto es puramente aditivo, no toca ninguna fila existente ni nada que
-- ya apunte a un district_id.

INSERT INTO public.districts (name, city) VALUES
  ('Abancay', 'Abancay'),
  ('Chacoche', 'Abancay'),
  ('Circa', 'Abancay'),
  ('Curahuasi', 'Abancay'),
  ('Huanipaca', 'Abancay'),
  ('Lambrama', 'Abancay'),
  ('Pichirhua', 'Abancay'),
  ('San Pedro de Cachora', 'Abancay'),
  ('Tamburco', 'Abancay'),
  ('Acobamba', 'Acobamba'),
  ('Andabamba', 'Acobamba'),
  ('Anta', 'Acobamba'),
  ('Caja', 'Acobamba'),
  ('Marcas', 'Acobamba'),
  ('Paucara', 'Acobamba'),
  ('Pomacocha', 'Acobamba'),
  ('Rosario', 'Acobamba'),
  ('Acomayo', 'Acomayo'),
  ('Acopia', 'Acomayo'),
  ('Acos', 'Acomayo'),
  ('Mosoc Llacta', 'Acomayo'),
  ('Pomacanchi', 'Acomayo'),
  ('Rondocan', 'Acomayo'),
  ('Sangarara', 'Acomayo'),
  ('Aija', 'Aija'),
  ('Coris', 'Aija'),
  ('Huacllan', 'Aija'),
  ('La Merced', 'Aija'),
  ('Succha', 'Aija'),
  ('Balsapuerto', 'Alto Amazonas'),
  ('Barranca', 'Alto Amazonas'),
  ('Cahuapanas', 'Alto Amazonas'),
  ('Jeberos', 'Alto Amazonas'),
  ('Lagunas', 'Alto Amazonas'),
  ('Manseriche', 'Alto Amazonas'),
  ('Morona', 'Alto Amazonas'),
  ('Pastaza', 'Alto Amazonas'),
  ('Santa Cruz', 'Alto Amazonas'),
  ('Teniente Cesar Lopez Rojas', 'Alto Amazonas'),
  ('Yurimaguas', 'Alto Amazonas'),
  ('Ambo', 'Ambo'),
  ('Cayna', 'Ambo'),
  ('Colpas', 'Ambo'),
  ('Conchamarca', 'Ambo'),
  ('Huacar', 'Ambo'),
  ('San Francisco', 'Ambo'),
  ('San Rafael', 'Ambo'),
  ('Tomay Kichwa', 'Ambo'),
  ('Andahuaylas', 'Andahuaylas'),
  ('Andarapa', 'Andahuaylas'),
  ('Chiara', 'Andahuaylas'),
  ('Huancarama', 'Andahuaylas'),
  ('Huancaray', 'Andahuaylas'),
  ('Huayana', 'Andahuaylas'),
  ('Kaquiabamba', 'Andahuaylas'),
  ('Kishuara', 'Andahuaylas'),
  ('Pacobamba', 'Andahuaylas'),
  ('Pacucha', 'Andahuaylas'),
  ('Pampachiri', 'Andahuaylas'),
  ('Pomacocha', 'Andahuaylas'),
  ('San Antonio de Cachi', 'Andahuaylas'),
  ('San Jeronimo', 'Andahuaylas'),
  ('San Miguel de Chaccrampa', 'Andahuaylas'),
  ('Santa Maria de Chicmo', 'Andahuaylas'),
  ('Talavera', 'Andahuaylas'),
  ('Tumay Huaraca', 'Andahuaylas'),
  ('Turpo', 'Andahuaylas'),
  ('Anchonga', 'Angaraes'),
  ('Callanmarca', 'Angaraes'),
  ('Ccochaccasa', 'Angaraes'),
  ('Chincho', 'Angaraes'),
  ('Congalla', 'Angaraes'),
  ('Huanca-Huanca', 'Angaraes'),
  ('Huayllay Grande', 'Angaraes'),
  ('Julcamarca', 'Angaraes'),
  ('Lircay', 'Angaraes'),
  ('San Antonio de Antaparco', 'Angaraes'),
  ('Santo Tomas de Pata', 'Angaraes'),
  ('Secclla', 'Angaraes'),
  ('Ancahuasi', 'Anta'),
  ('Anta', 'Anta'),
  ('Cachimayo', 'Anta'),
  ('Chinchaypujio', 'Anta'),
  ('Huarocondo', 'Anta'),
  ('Limatambo', 'Anta'),
  ('Mollepata', 'Anta'),
  ('Pucyura', 'Anta'),
  ('Zurite', 'Anta'),
  ('Antabamba', 'Antabamba'),
  ('El Oro', 'Antabamba'),
  ('Huaquirca', 'Antabamba'),
  ('Juan Espinoza Medrano', 'Antabamba'),
  ('Oropesa', 'Antabamba'),
  ('Pachaconas', 'Antabamba'),
  ('Sabaino', 'Antabamba'),
  ('Aczo', 'Antonio Raymondi'),
  ('Chaccho', 'Antonio Raymondi'),
  ('Chingas', 'Antonio Raymondi'),
  ('Llamellin', 'Antonio Raymondi'),
  ('Mirgas', 'Antonio Raymondi'),
  ('San Juan de Rontoy', 'Antonio Raymondi'),
  ('Alto Selva Alegre', 'Arequipa'),
  ('Arequipa', 'Arequipa'),
  ('Cayma', 'Arequipa'),
  ('Cerro Colorado', 'Arequipa'),
  ('Characato', 'Arequipa'),
  ('Chiguata', 'Arequipa'),
  ('Jacobo Hunter', 'Arequipa'),
  ('José Luis Bustamante y Rivero', 'Arequipa'),
  ('La Joya', 'Arequipa'),
  ('Mariano Melgar', 'Arequipa'),
  ('Miraflores', 'Arequipa'),
  ('Mollebaya', 'Arequipa'),
  ('Paucarpata', 'Arequipa'),
  ('Pocsi', 'Arequipa'),
  ('Polobaya', 'Arequipa'),
  ('Quequeña', 'Arequipa'),
  ('Sabandía', 'Arequipa'),
  ('Sachaca', 'Arequipa'),
  ('San Juan de Siguas', 'Arequipa'),
  ('San Juan de Tarucani', 'Arequipa'),
  ('Santa Isabel de Siguas', 'Arequipa'),
  ('Santa Rita de Siguas', 'Arequipa'),
  ('Socabaya', 'Arequipa'),
  ('Tiabaya', 'Arequipa'),
  ('Uchumayo', 'Arequipa'),
  ('Vítor', 'Arequipa'),
  ('Yanahuara', 'Arequipa'),
  ('Yarabamba', 'Arequipa'),
  ('Yura', 'Arequipa'),
  ('Ascope', 'Ascope'),
  ('Casa Grande', 'Ascope'),
  ('Chicama', 'Ascope'),
  ('Chocope', 'Ascope'),
  ('Magdalena de Cao', 'Ascope'),
  ('Paijan', 'Ascope'),
  ('Razuri', 'Ascope'),
  ('Santiago de Cao', 'Ascope'),
  ('Acochaca', 'Asuncion'),
  ('Chacas', 'Asuncion'),
  ('Raymondi', 'Atalaya'),
  ('Sepahua', 'Atalaya'),
  ('Tahuania', 'Atalaya'),
  ('Yurua', 'Atalaya'),
  ('Ayabaca', 'Ayabaca'),
  ('Frias', 'Ayabaca'),
  ('Jilili', 'Ayabaca'),
  ('Lagunas', 'Ayabaca'),
  ('Montero', 'Ayabaca'),
  ('Pacaipampa', 'Ayabaca'),
  ('Paimas', 'Ayabaca'),
  ('Sapillica', 'Ayabaca'),
  ('Sicchez', 'Ayabaca'),
  ('Suyo', 'Ayabaca'),
  ('Capaya', 'Aymaraes'),
  ('Caraybamba', 'Aymaraes'),
  ('Chalhuanca', 'Aymaraes'),
  ('Chapimarca', 'Aymaraes'),
  ('Colcabamba', 'Aymaraes'),
  ('Cotaruse', 'Aymaraes'),
  ('Huayllo', 'Aymaraes'),
  ('Justo Apu Sahuaraura', 'Aymaraes'),
  ('Lucre', 'Aymaraes'),
  ('Pocohuanca', 'Aymaraes'),
  ('San Juan de Chacqa', 'Aymaraes'),
  ('Saqayca', 'Aymaraes'),
  ('Soraya', 'Aymaraes'),
  ('Tapairihua', 'Aymaraes'),
  ('Tintay', 'Aymaraes'),
  ('Toraya', 'Aymaraes'),
  ('Yanaca', 'Aymaraes'),
  ('Achaya', 'Azangaro'),
  ('Arapa', 'Azangaro'),
  ('Asillo', 'Azangaro'),
  ('Azangaro', 'Azangaro'),
  ('Caminaca', 'Azangaro'),
  ('Chupa', 'Azangaro'),
  ('Jose Domingo Choquehuanca', 'Azangaro'),
  ('Muqani', 'Azangaro'),
  ('Potoni', 'Azangaro'),
  ('Saman', 'Azangaro'),
  ('San Anton', 'Azangaro'),
  ('San Jose', 'Azangaro'),
  ('San Juan de Salinas', 'Azangaro'),
  ('Santiago de Pupuja', 'Azangaro'),
  ('Tirapata', 'Azangaro'),
  ('Aramango', 'Bagua'),
  ('Copallin', 'Bagua'),
  ('El Parco', 'Bagua'),
  ('Imaza', 'Bagua'),
  ('La Peca', 'Bagua'),
  ('Barranca', 'Barranca'),
  ('Paramonga', 'Barranca'),
  ('Pativilca', 'Barranca'),
  ('Supe', 'Barranca'),
  ('Supe Puerto', 'Barranca'),
  ('Alto Biavo', 'Bellavista'),
  ('Bajo Biavo', 'Bellavista'),
  ('Bellavista', 'Bellavista'),
  ('Huallaga', 'Bellavista'),
  ('San Pablo', 'Bellavista'),
  ('San Rafael', 'Bellavista'),
  ('Bambamarca', 'Bolivar'),
  ('Bolivar', 'Bolivar'),
  ('Condormarca', 'Bolivar'),
  ('Longotea', 'Bolivar'),
  ('Uchumarca', 'Bolivar'),
  ('Ucuncha', 'Bolivar'),
  ('Abelardo Pardo Lezameta', 'Bolognesi'),
  ('Antonio Raymondi', 'Bolognesi'),
  ('Aquia', 'Bolognesi'),
  ('Cajacay', 'Bolognesi'),
  ('Canis', 'Bolognesi'),
  ('Chiquian', 'Bolognesi'),
  ('Colquioc', 'Bolognesi'),
  ('Huallanca', 'Bolognesi'),
  ('Huasta', 'Bolognesi'),
  ('Huayllacayan', 'Bolognesi'),
  ('La Primavera', 'Bolognesi'),
  ('Mangas', 'Bolognesi'),
  ('Pacllon', 'Bolognesi'),
  ('San Miguel de Corpanqui', 'Bolognesi'),
  ('Ticllos', 'Bolognesi'),
  ('Chisquilla', 'Bongara'),
  ('Churuja', 'Bongara'),
  ('Corosha', 'Bongara'),
  ('Cuispes', 'Bongara'),
  ('Florida', 'Bongara'),
  ('Jazan', 'Bongara'),
  ('Jumbilla', 'Bongara'),
  ('Recta', 'Bongara'),
  ('San Carlos', 'Bongara'),
  ('Shipasbamba', 'Bongara'),
  ('Valera', 'Bongara'),
  ('Yambrasbamba', 'Bongara'),
  ('Cachachi', 'Cajabamba'),
  ('Cajabamba', 'Cajabamba'),
  ('Condebamba', 'Cajabamba'),
  ('Sitacocha', 'Cajabamba'),
  ('Asuncion', 'Cajamarca'),
  ('Cajamarca', 'Cajamarca'),
  ('Chetilla', 'Cajamarca'),
  ('Cospan', 'Cajamarca'),
  ('Encaqada', 'Cajamarca'),
  ('Jesus', 'Cajamarca'),
  ('Llacanora', 'Cajamarca'),
  ('Los Baqos del Inca', 'Cajamarca'),
  ('Magdalena', 'Cajamarca'),
  ('Matara', 'Cajamarca'),
  ('Namora', 'Cajamarca'),
  ('San Juan', 'Cajamarca'),
  ('Cajatambo', 'Cajatambo'),
  ('Copa', 'Cajatambo'),
  ('Gorgor', 'Cajatambo'),
  ('Huancapon', 'Cajatambo'),
  ('Manas', 'Cajatambo'),
  ('Calca', 'Calca'),
  ('Coya', 'Calca'),
  ('Lamay', 'Calca'),
  ('Lares', 'Calca'),
  ('Pisac', 'Calca'),
  ('San Salvador', 'Calca'),
  ('Taray', 'Calca'),
  ('Yanatile', 'Calca'),
  ('Bellavista', 'Callao'),
  ('Callao', 'Callao'),
  ('Carmen de la Legua Reynoso', 'Callao'),
  ('La Perla', 'Callao'),
  ('La Punta', 'Callao'),
  ('Ventanilla', 'Callao'),
  ('Camana', 'Camana'),
  ('Jose Maria Quimper', 'Camana'),
  ('Mariano Nicolas Valcarcel', 'Camana'),
  ('Mariscal Caceres', 'Camana'),
  ('Nicolas de Pierola', 'Camana'),
  ('Ocoqa', 'Camana'),
  ('Quilca', 'Camana'),
  ('Samuel Pastor', 'Camana'),
  ('Checca', 'Canas'),
  ('Kunturkanki', 'Canas'),
  ('Langui', 'Canas'),
  ('Layo', 'Canas'),
  ('Pampamarca', 'Canas'),
  ('Quehue', 'Canas'),
  ('Tupac Amaru', 'Canas'),
  ('Yanaoca', 'Canas'),
  ('Checacupe', 'Canchis'),
  ('Combapata', 'Canchis'),
  ('Marangani', 'Canchis'),
  ('Pitumarca', 'Canchis'),
  ('San Pablo', 'Canchis'),
  ('San Pedro', 'Canchis'),
  ('Sicuani', 'Canchis'),
  ('Tinta', 'Canchis'),
  ('Cairani', 'Candarave'),
  ('Camilaca', 'Candarave'),
  ('Candarave', 'Candarave'),
  ('Curibaya', 'Candarave'),
  ('Huanuara', 'Candarave'),
  ('Quilahuani', 'Candarave'),
  ('Cangallo', 'Cangallo'),
  ('Chuschi', 'Cangallo'),
  ('Los Morochucos', 'Cangallo'),
  ('Maria Parado de Bellido', 'Cangallo'),
  ('Paras', 'Cangallo'),
  ('Totos', 'Cangallo'),
  ('Arahuay', 'Canta'),
  ('Canta', 'Canta'),
  ('Huamantanga', 'Canta'),
  ('Huaros', 'Canta'),
  ('Lachaqui', 'Canta'),
  ('San Buenaventura', 'Canta'),
  ('Santa Rosa de Quives', 'Canta'),
  ('Ajoyani', 'Carabaya'),
  ('Ayapata', 'Carabaya'),
  ('Coasa', 'Carabaya'),
  ('Corani', 'Carabaya'),
  ('Crucero', 'Carabaya'),
  ('Ituata', 'Carabaya'),
  ('Macusani', 'Carabaya'),
  ('Ollachea', 'Carabaya'),
  ('San Gaban', 'Carabaya'),
  ('Usicayos', 'Carabaya'),
  ('Acari', 'Caraveli'),
  ('Atico', 'Caraveli'),
  ('Atiquipa', 'Caraveli'),
  ('Bella Union', 'Caraveli'),
  ('Cahuacho', 'Caraveli'),
  ('Caraveli', 'Caraveli'),
  ('Chala', 'Caraveli'),
  ('Chaparra', 'Caraveli'),
  ('Huanuhuanu', 'Caraveli'),
  ('Jaqui', 'Caraveli'),
  ('Lomas', 'Caraveli'),
  ('Quicacha', 'Caraveli'),
  ('Yauca', 'Caraveli'),
  ('Acopampa', 'Carhuaz'),
  ('Amashca', 'Carhuaz'),
  ('Anta', 'Carhuaz'),
  ('Ataquero', 'Carhuaz'),
  ('Carhuaz', 'Carhuaz'),
  ('Marcara', 'Carhuaz'),
  ('Pariahuanca', 'Carhuaz'),
  ('San Miguel de Aco', 'Carhuaz'),
  ('Shilla', 'Carhuaz'),
  ('Tinco', 'Carhuaz'),
  ('Yungar', 'Carhuaz'),
  ('San Luis', 'Carlos Fermin Fitzcarrald'),
  ('San Nicolas', 'Carlos Fermin Fitzcarrald'),
  ('Yauya', 'Carlos Fermin Fitzcarrald'),
  ('Buena Vista Alta', 'Casma'),
  ('Casma', 'Casma'),
  ('Comandante Noel', 'Casma'),
  ('Yautan', 'Casma'),
  ('Andagua', 'Castilla'),
  ('Aplao', 'Castilla'),
  ('Ayo', 'Castilla'),
  ('Chachas', 'Castilla'),
  ('Chilcaymarca', 'Castilla'),
  ('Choco', 'Castilla'),
  ('Huancarqui', 'Castilla'),
  ('Machaguay', 'Castilla'),
  ('Majes', 'Castilla'),
  ('Orcopampa', 'Castilla'),
  ('Pampacolca', 'Castilla'),
  ('Tipan', 'Castilla'),
  ('Uqon', 'Castilla'),
  ('Uraca', 'Castilla'),
  ('Viraco', 'Castilla'),
  ('Yanque', 'Castilla'),
  ('Arma', 'Castrovirreyna'),
  ('Aurahua', 'Castrovirreyna'),
  ('Capillas', 'Castrovirreyna'),
  ('Castrovirreyna', 'Castrovirreyna'),
  ('Chupamarca', 'Castrovirreyna'),
  ('Cocas', 'Castrovirreyna'),
  ('Huachos', 'Castrovirreyna'),
  ('Huamatambo', 'Castrovirreyna'),
  ('Mollepampa', 'Castrovirreyna'),
  ('San Juan', 'Castrovirreyna'),
  ('Santa Ana', 'Castrovirreyna'),
  ('Tantara', 'Castrovirreyna'),
  ('Ticrapo', 'Castrovirreyna'),
  ('Achoma', 'Caylloma'),
  ('Cabanaconde', 'Caylloma'),
  ('Callalli', 'Caylloma'),
  ('Caylloma', 'Caylloma'),
  ('Chivay', 'Caylloma'),
  ('Coporaque', 'Caylloma'),
  ('Huambo', 'Caylloma'),
  ('Huanca', 'Caylloma'),
  ('Ichupampa', 'Caylloma'),
  ('Lari', 'Caylloma'),
  ('Lluta', 'Caylloma'),
  ('Maca', 'Caylloma'),
  ('Madrigal', 'Caylloma'),
  ('Majes', 'Caylloma'),
  ('San Antonio de Chuca', 'Caylloma'),
  ('Sibayo', 'Caylloma'),
  ('Tapay', 'Caylloma'),
  ('Tisco', 'Caylloma'),
  ('Tuti', 'Caylloma'),
  ('Yanque', 'Caylloma'),
  ('Asia', 'Cañete'),
  ('Calango', 'Cañete'),
  ('Cerro Azul', 'Cañete'),
  ('Chilca', 'Cañete'),
  ('Coayllo', 'Cañete'),
  ('Imperial', 'Cañete'),
  ('Lunahuana', 'Cañete'),
  ('Mala', 'Cañete'),
  ('Nuevo Imperial', 'Cañete'),
  ('Pacaran', 'Cañete'),
  ('Quilmana', 'Cañete'),
  ('San Antonio', 'Cañete'),
  ('San Luis', 'Cañete'),
  ('San Vicente de Cañete', 'Cañete'),
  ('Santa Cruz de Flores', 'Cañete'),
  ('Zuqiga', 'Cañete'),
  ('Celendin', 'Celendin'),
  ('Chumuch', 'Celendin'),
  ('Cortegana', 'Celendin'),
  ('Huasmin', 'Celendin'),
  ('Jorge Chavez', 'Celendin'),
  ('Jose Galvez', 'Celendin'),
  ('La Libertad de Pallan', 'Celendin'),
  ('Miguel Iglesias', 'Celendin'),
  ('Oxamarca', 'Celendin'),
  ('Sorochuco', 'Celendin'),
  ('Sucre', 'Celendin'),
  ('Utco', 'Celendin'),
  ('Asuncion', 'Chachapoyas'),
  ('Balsas', 'Chachapoyas'),
  ('Chachapoyas', 'Chachapoyas'),
  ('Cheto', 'Chachapoyas'),
  ('Chiliquin', 'Chachapoyas'),
  ('Chuquibamba', 'Chachapoyas'),
  ('Granada', 'Chachapoyas'),
  ('Huancas', 'Chachapoyas'),
  ('La Jalca', 'Chachapoyas'),
  ('Leimebamba', 'Chachapoyas'),
  ('Levanto', 'Chachapoyas'),
  ('Magdalena', 'Chachapoyas'),
  ('Mariscal Castilla', 'Chachapoyas'),
  ('Molinopampa', 'Chachapoyas'),
  ('Montevideo', 'Chachapoyas'),
  ('Olleros', 'Chachapoyas'),
  ('Quinjalca', 'Chachapoyas'),
  ('San Francisco de Daguas', 'Chachapoyas'),
  ('San Isidro de Maino', 'Chachapoyas'),
  ('Soloco', 'Chachapoyas'),
  ('Sonche', 'Chachapoyas'),
  ('Chanchamayo', 'Chanchamayo'),
  ('Perene', 'Chanchamayo'),
  ('Pichanaqui', 'Chanchamayo'),
  ('San Luis de Shuaro', 'Chanchamayo'),
  ('San Ramon', 'Chanchamayo'),
  ('Vitoc', 'Chanchamayo'),
  ('Chepen', 'Chepen'),
  ('Pacanga', 'Chepen'),
  ('Pueblo Nuevo', 'Chepen'),
  ('Cayaltí', 'Chiclayo'),
  ('Chiclayo', 'Chiclayo'),
  ('Chongoyape', 'Chiclayo'),
  ('Eten', 'Chiclayo'),
  ('Eten Puerto', 'Chiclayo'),
  ('José Leonardo Ortiz', 'Chiclayo'),
  ('La Victoria', 'Chiclayo'),
  ('Lagunas', 'Chiclayo'),
  ('Monsefú', 'Chiclayo'),
  ('Nueva Arica', 'Chiclayo'),
  ('Oyotún', 'Chiclayo'),
  ('Picsi', 'Chiclayo'),
  ('Pimentel', 'Chiclayo'),
  ('Pomalca', 'Chiclayo'),
  ('Pucalá', 'Chiclayo'),
  ('Pátapo', 'Chiclayo'),
  ('Reque', 'Chiclayo'),
  ('Santa Rosa', 'Chiclayo'),
  ('Tumán', 'Chiclayo'),
  ('Zaña', 'Chiclayo'),
  ('Alto Laran', 'Chincha'),
  ('Chavin', 'Chincha'),
  ('Chincha Alta', 'Chincha'),
  ('Chincha Baja', 'Chincha'),
  ('El Carmen', 'Chincha'),
  ('Grocio Prado', 'Chincha'),
  ('Pueblo Nuevo', 'Chincha'),
  ('San Juan de Yanac', 'Chincha'),
  ('San Pedro de Huacarpana', 'Chincha'),
  ('Sunampe', 'Chincha'),
  ('Tambo de Mora', 'Chincha'),
  ('Anco-Huallo', 'Chincheros'),
  ('Chincheros', 'Chincheros'),
  ('Cocharcas', 'Chincheros'),
  ('Huaccana', 'Chincheros'),
  ('Ocobamba', 'Chincheros'),
  ('Ongoy', 'Chincheros'),
  ('Ranracancha', 'Chincheros'),
  ('Uranmarca', 'Chincheros'),
  ('Anguia', 'Chota'),
  ('Chadin', 'Chota'),
  ('Chalamarca', 'Chota'),
  ('Chiguirip', 'Chota'),
  ('Chimban', 'Chota'),
  ('Choropampa', 'Chota'),
  ('Chota', 'Chota'),
  ('Cochabamba', 'Chota'),
  ('Conchan', 'Chota'),
  ('Huambos', 'Chota'),
  ('Lajas', 'Chota'),
  ('Llama', 'Chota'),
  ('Miracosta', 'Chota'),
  ('Paccha', 'Chota'),
  ('Pion', 'Chota'),
  ('Querocoto', 'Chota'),
  ('San Juan de Licupis', 'Chota'),
  ('Tacabamba', 'Chota'),
  ('Tocmoche', 'Chota'),
  ('Desaguadero', 'Chucuito'),
  ('Huacullani', 'Chucuito'),
  ('Juli', 'Chucuito'),
  ('Kelluyo', 'Chucuito'),
  ('Pisacoma', 'Chucuito'),
  ('Pomata', 'Chucuito'),
  ('Zepita', 'Chucuito'),
  ('Capacmarca', 'Chumbivilcas'),
  ('Chamaca', 'Chumbivilcas'),
  ('Colquemarca', 'Chumbivilcas'),
  ('Livitaca', 'Chumbivilcas'),
  ('Llusco', 'Chumbivilcas'),
  ('Quiqota', 'Chumbivilcas'),
  ('Santo Tomas', 'Chumbivilcas'),
  ('Velille', 'Chumbivilcas'),
  ('Ahuac', 'Chupaca'),
  ('Chongos Bajo', 'Chupaca'),
  ('Chupaca', 'Chupaca'),
  ('Huachac', 'Chupaca'),
  ('Huamancaca Chico', 'Chupaca'),
  ('San Juan de Iscos', 'Chupaca'),
  ('San Juan de Jarpa', 'Chupaca'),
  ('Tres de Diciembre', 'Chupaca'),
  ('Yanacancha', 'Chupaca'),
  ('Anco', 'Churcampa'),
  ('Chinchihuasi', 'Churcampa'),
  ('Churcampa', 'Churcampa'),
  ('El Carmen', 'Churcampa'),
  ('La Merced', 'Churcampa'),
  ('Locroja', 'Churcampa'),
  ('Pachamarca', 'Churcampa'),
  ('Paucarbamba', 'Churcampa'),
  ('San Miguel de Mayocc', 'Churcampa'),
  ('San Pedro de Coris', 'Churcampa'),
  ('Aco', 'Concepcion'),
  ('Andamarca', 'Concepcion'),
  ('Chambara', 'Concepcion'),
  ('Cochas', 'Concepcion'),
  ('Comas', 'Concepcion'),
  ('Concepcion', 'Concepcion'),
  ('Heroinas Toledo', 'Concepcion'),
  ('Manzanares', 'Concepcion'),
  ('Mariscal Castilla', 'Concepcion'),
  ('Matahuasi', 'Concepcion'),
  ('Mito', 'Concepcion'),
  ('Nueve de Julio', 'Concepcion'),
  ('Orcotuna', 'Concepcion'),
  ('San Jose de Quero', 'Concepcion'),
  ('Santa Rosa de Ocopa', 'Concepcion'),
  ('Andaray', 'Condesuyos'),
  ('Cayarani', 'Condesuyos'),
  ('Chichas', 'Condesuyos'),
  ('Chuquibamba', 'Condesuyos'),
  ('Iray', 'Condesuyos'),
  ('Rio Grande', 'Condesuyos'),
  ('Salamanca', 'Condesuyos'),
  ('Yanaquihua', 'Condesuyos'),
  ('El Cenepa', 'Condorcanqui'),
  ('Nieva', 'Condorcanqui'),
  ('Rio Santiago', 'Condorcanqui'),
  ('Casitas', 'Contralmirante Villar'),
  ('Zorritos', 'Contralmirante Villar'),
  ('Chilete', 'Contumaza'),
  ('Contumaza', 'Contumaza'),
  ('Cupisnique', 'Contumaza'),
  ('Guzmango', 'Contumaza'),
  ('San Benito', 'Contumaza'),
  ('Santa Cruz de Toled', 'Contumaza'),
  ('Tantarica', 'Contumaza'),
  ('Yonan', 'Contumaza'),
  ('Calleria', 'Coronel Portillo'),
  ('Campoverde', 'Coronel Portillo'),
  ('Iparia', 'Coronel Portillo'),
  ('Masisea', 'Coronel Portillo'),
  ('Nueva Requena', 'Coronel Portillo'),
  ('Yarinacocha', 'Coronel Portillo'),
  ('Aco', 'Corongo'),
  ('Bambas', 'Corongo'),
  ('Corongo', 'Corongo'),
  ('Cusca', 'Corongo'),
  ('La Pampa', 'Corongo'),
  ('Yanac', 'Corongo'),
  ('Yupan', 'Corongo'),
  ('Challhuahuacho', 'Cotabambas'),
  ('Cotabambas', 'Cotabambas'),
  ('Coyllurqui', 'Cotabambas'),
  ('Haquira', 'Cotabambas'),
  ('Mara', 'Cotabambas'),
  ('Tambobamba', 'Cotabambas'),
  ('Ccorca', 'Cusco'),
  ('Cusco', 'Cusco'),
  ('Poroy', 'Cusco'),
  ('San Jerónimo', 'Cusco'),
  ('San Sebastián', 'Cusco'),
  ('Santiago', 'Cusco'),
  ('Saylla', 'Cusco'),
  ('Wanchaq', 'Cusco'),
  ('Callayuc', 'Cutervo'),
  ('Choros', 'Cutervo'),
  ('Cujillo', 'Cutervo'),
  ('Cutervo', 'Cutervo'),
  ('La Ramada', 'Cutervo'),
  ('Pimpingos', 'Cutervo'),
  ('Querocotillo', 'Cutervo'),
  ('San Andres de Cutervo', 'Cutervo'),
  ('San Juan de Cutervo', 'Cutervo'),
  ('San Luis de Lucma', 'Cutervo'),
  ('Santa Cruz', 'Cutervo'),
  ('Santo Domingo de la Capilla', 'Cutervo'),
  ('Santo Tomas', 'Cutervo'),
  ('Socota', 'Cutervo'),
  ('Toribio Casanova', 'Cutervo'),
  ('Chacayan', 'Daniel Alcides Carrion'),
  ('Goyllarisquizga', 'Daniel Alcides Carrion'),
  ('Paucar', 'Daniel Alcides Carrion'),
  ('San Pedro de Pillao', 'Daniel Alcides Carrion'),
  ('Santa Ana de Tusi', 'Daniel Alcides Carrion'),
  ('Tapuc', 'Daniel Alcides Carrion'),
  ('Vilcabamba', 'Daniel Alcides Carrion'),
  ('Yanahuanca', 'Daniel Alcides Carrion'),
  ('Chuquis', 'Dos de Mayo'),
  ('La Union', 'Dos de Mayo'),
  ('Marias', 'Dos de Mayo'),
  ('Pachas', 'Dos de Mayo'),
  ('Quivilla', 'Dos de Mayo'),
  ('Ripan', 'Dos de Mayo'),
  ('Shunqui', 'Dos de Mayo'),
  ('Sillapata', 'Dos de Mayo'),
  ('Yanas', 'Dos de Mayo'),
  ('Capazo', 'El Collao'),
  ('Conduriri', 'El Collao'),
  ('Ilave', 'El Collao'),
  ('Pilcuyo', 'El Collao'),
  ('Santa Rosa', 'El Collao'),
  ('Agua Blanca', 'El Dorado'),
  ('San Jose de Sisa', 'El Dorado'),
  ('San Martin', 'El Dorado'),
  ('Santa Rosa', 'El Dorado'),
  ('Shatoja', 'El Dorado'),
  ('Alto Pichigua', 'Espinar'),
  ('Condoroma', 'Espinar'),
  ('Coporaque', 'Espinar'),
  ('Espinar', 'Espinar'),
  ('Ocoruro', 'Espinar'),
  ('Pallpata', 'Espinar'),
  ('Pichigua', 'Espinar'),
  ('Suyckutambo', 'Espinar'),
  ('Caqaris', 'Ferreqafe'),
  ('Ferreqafe', 'Ferreqafe'),
  ('Incahuasi', 'Ferreqafe'),
  ('Manuel Antonio Mesones Muro', 'Ferreqafe'),
  ('Pitipo', 'Ferreqafe'),
  ('Pueblo Nuevo', 'Ferreqafe'),
  ('Chojata', 'General Sanchez Cerro'),
  ('Coalaque', 'General Sanchez Cerro'),
  ('Ichuqa', 'General Sanchez Cerro'),
  ('La Capilla', 'General Sanchez Cerro'),
  ('Lloque', 'General Sanchez Cerro'),
  ('Matalaque', 'General Sanchez Cerro'),
  ('Omate', 'General Sanchez Cerro'),
  ('Puquina', 'General Sanchez Cerro'),
  ('Quinistaquillas', 'General Sanchez Cerro'),
  ('Ubinas', 'General Sanchez Cerro'),
  ('Yunga', 'General Sanchez Cerro'),
  ('Cascas', 'Gran Chimu'),
  ('Lucma', 'Gran Chimu'),
  ('Marmot', 'Gran Chimu'),
  ('Sayapullo', 'Gran Chimu'),
  ('Chuquibambilla', 'Grau'),
  ('Curasco', 'Grau'),
  ('Curpahuasi', 'Grau'),
  ('Gamarra', 'Grau'),
  ('Huayllati', 'Grau'),
  ('Mamara', 'Grau'),
  ('Micaela Bastidas', 'Grau'),
  ('Pataypampa', 'Grau'),
  ('Progreso', 'Grau'),
  ('San Antonio', 'Grau'),
  ('Santa Rosa', 'Grau'),
  ('Turpay', 'Grau'),
  ('Vilcabamba', 'Grau'),
  ('Virundo', 'Grau'),
  ('Canchabamba', 'Huacaybamba'),
  ('Cochabamba', 'Huacaybamba'),
  ('Huacaybamba', 'Huacaybamba'),
  ('Pinra', 'Huacaybamba'),
  ('Bambamarca', 'Hualgayoc'),
  ('Chugur', 'Hualgayoc'),
  ('Hualgayoc', 'Hualgayoc'),
  ('Alto Saposoa', 'Huallaga'),
  ('El Eslabon', 'Huallaga'),
  ('Piscoyacu', 'Huallaga'),
  ('Sacanche', 'Huallaga'),
  ('Saposoa', 'Huallaga'),
  ('Tingo de Saposoa', 'Huallaga'),
  ('Arancay', 'Huamalies'),
  ('Chavin de Pariarca', 'Huamalies'),
  ('Jacas Grande', 'Huamalies'),
  ('Jircan', 'Huamalies'),
  ('Llata', 'Huamalies'),
  ('Miraflores', 'Huamalies'),
  ('Monzon', 'Huamalies'),
  ('Punchao', 'Huamalies'),
  ('Puqos', 'Huamalies'),
  ('Singa', 'Huamalies'),
  ('Tantamayo', 'Huamalies'),
  ('Acocro', 'Huamanga'),
  ('Acos Vinchos', 'Huamanga'),
  ('Ayacucho', 'Huamanga'),
  ('Carmen Alto', 'Huamanga'),
  ('Chiara', 'Huamanga'),
  ('Jesús Nazareno', 'Huamanga'),
  ('Ocros', 'Huamanga'),
  ('Pacaycasa', 'Huamanga'),
  ('Quinua', 'Huamanga'),
  ('San Jose de Ticllas', 'Huamanga'),
  ('San Juan Bautista', 'Huamanga'),
  ('Santiago de Pischa', 'Huamanga'),
  ('Socos', 'Huamanga'),
  ('Tambillo', 'Huamanga'),
  ('Vinchos', 'Huamanga'),
  ('Carapo', 'Huanca Sancos'),
  ('Sacsamarca', 'Huanca Sancos'),
  ('Sancos', 'Huanca Sancos'),
  ('Santiago de Lucanamarca', 'Huanca Sancos'),
  ('Canchaque', 'Huancabamba'),
  ('El Carmen de la Frontera', 'Huancabamba'),
  ('Huancabamba', 'Huancabamba'),
  ('Huarmaca', 'Huancabamba'),
  ('Lalaquiz', 'Huancabamba'),
  ('San Miguel de El Faique', 'Huancabamba'),
  ('Sondor', 'Huancabamba'),
  ('Sondorillo', 'Huancabamba'),
  ('Cojata', 'Huancane'),
  ('Huancane', 'Huancane'),
  ('Huatasani', 'Huancane'),
  ('Inchupalla', 'Huancane'),
  ('Pusi', 'Huancane'),
  ('Rosaspata', 'Huancane'),
  ('Taraco', 'Huancane'),
  ('Vilque Chico', 'Huancane'),
  ('Acobambilla', 'Huancavelica'),
  ('Acoria', 'Huancavelica'),
  ('Ascensión', 'Huancavelica'),
  ('Conayca', 'Huancavelica'),
  ('Cuenca', 'Huancavelica'),
  ('Huachocolpa', 'Huancavelica'),
  ('Huancavelica', 'Huancavelica'),
  ('Huando', 'Huancavelica'),
  ('Huayllahuara', 'Huancavelica'),
  ('Izcuchaca', 'Huancavelica'),
  ('Laria', 'Huancavelica'),
  ('Manta', 'Huancavelica'),
  ('Mariscal Caceres', 'Huancavelica'),
  ('Moya', 'Huancavelica'),
  ('Nuevo Occoro', 'Huancavelica'),
  ('Palca', 'Huancavelica'),
  ('Pilchaca', 'Huancavelica'),
  ('Vilca', 'Huancavelica'),
  ('Yauli', 'Huancavelica'),
  ('Carhuacallanga', 'Huancayo'),
  ('Chacapampa', 'Huancayo'),
  ('Chicche', 'Huancayo'),
  ('Chilca', 'Huancayo'),
  ('Chongos Alto', 'Huancayo'),
  ('Chupuro', 'Huancayo'),
  ('Colca', 'Huancayo'),
  ('Cullhuas', 'Huancayo'),
  ('El Tambo', 'Huancayo'),
  ('Huacrapuquio', 'Huancayo'),
  ('Hualhuas', 'Huancayo'),
  ('Huancan', 'Huancayo'),
  ('Huancayo', 'Huancayo'),
  ('Huasicancha', 'Huancayo'),
  ('Huayucachi', 'Huancayo'),
  ('Ingenio', 'Huancayo'),
  ('Pariahuanca', 'Huancayo'),
  ('Pilcomayo', 'Huancayo'),
  ('Pucara', 'Huancayo'),
  ('Quichuay', 'Huancayo'),
  ('Quilcas', 'Huancayo'),
  ('San Agustin', 'Huancayo'),
  ('San Jeronimo de Tunan', 'Huancayo'),
  ('Santo Domingo de Acobamba', 'Huancayo'),
  ('Sapallanga', 'Huancayo'),
  ('Saqo', 'Huancayo'),
  ('Sicaya', 'Huancayo'),
  ('Viques', 'Huancayo'),
  ('Ayahuanco', 'Huanta'),
  ('Huamanguilla', 'Huanta'),
  ('Huanta', 'Huanta'),
  ('Iguain', 'Huanta'),
  ('Llochegua', 'Huanta'),
  ('Luricocha', 'Huanta'),
  ('Santillana', 'Huanta'),
  ('Sivia', 'Huanta'),
  ('Amarilis', 'Huanuco'),
  ('Chinchao', 'Huanuco'),
  ('Churubamba', 'Huanuco'),
  ('Huanuco', 'Huanuco'),
  ('Margos', 'Huanuco'),
  ('Pillcomarca', 'Huanuco'),
  ('Quisqui', 'Huanuco'),
  ('San Francisco de Cayran', 'Huanuco'),
  ('San Pedro de Chaulan', 'Huanuco'),
  ('Santa Maria del Valle', 'Huanuco'),
  ('Yarumayo', 'Huanuco'),
  ('Atavillos Alto', 'Huaral'),
  ('Atavillos Bajo', 'Huaral'),
  ('Aucallama', 'Huaral'),
  ('Chancay', 'Huaral'),
  ('Huaral', 'Huaral'),
  ('Ihuari', 'Huaral'),
  ('Lampian', 'Huaral'),
  ('Pacaraos', 'Huaral'),
  ('San Miguel de Acos', 'Huaral'),
  ('Santa Cruz de Andamarca', 'Huaral'),
  ('Sumbilca', 'Huaral'),
  ('Veintisiete de Noviembre', 'Huaral'),
  ('Cochabamba', 'Huaraz'),
  ('Colcabamba', 'Huaraz'),
  ('Huanchay', 'Huaraz'),
  ('Huaraz', 'Huaraz'),
  ('Independencia', 'Huaraz'),
  ('Jangas', 'Huaraz'),
  ('La Libertad', 'Huaraz'),
  ('Olleros', 'Huaraz'),
  ('Pampas', 'Huaraz'),
  ('Pariacoto', 'Huaraz'),
  ('Pira', 'Huaraz'),
  ('Tarica', 'Huaraz'),
  ('Anra', 'Huari'),
  ('Cajay', 'Huari'),
  ('Chavin de Huantar', 'Huari'),
  ('Huacachi', 'Huari'),
  ('Huacchis', 'Huari'),
  ('Huachis', 'Huari'),
  ('Huantar', 'Huari'),
  ('Huari', 'Huari'),
  ('Masin', 'Huari'),
  ('Paucas', 'Huari'),
  ('Ponto', 'Huari'),
  ('Rahuapampa', 'Huari'),
  ('Rapayan', 'Huari'),
  ('San Marcos', 'Huari'),
  ('San Pedro de Chana', 'Huari'),
  ('Uco', 'Huari'),
  ('Cochapeti', 'Huarmey'),
  ('Culebras', 'Huarmey'),
  ('Huarmey', 'Huarmey'),
  ('Huayan', 'Huarmey'),
  ('Malvas', 'Huarmey'),
  ('Antioquia', 'Huarochiri'),
  ('Callahuanca', 'Huarochiri'),
  ('Carampoma', 'Huarochiri'),
  ('Chicla', 'Huarochiri'),
  ('Cuenca', 'Huarochiri'),
  ('Huachupampa', 'Huarochiri'),
  ('Huanza', 'Huarochiri'),
  ('Huarochiri', 'Huarochiri'),
  ('Lahuaytambo', 'Huarochiri'),
  ('Langa', 'Huarochiri'),
  ('Laraos', 'Huarochiri'),
  ('Mariatana', 'Huarochiri'),
  ('Matucana', 'Huarochiri'),
  ('Ricardo Palma', 'Huarochiri'),
  ('San Andres de Tupicocha', 'Huarochiri'),
  ('San Antonio', 'Huarochiri'),
  ('San Bartolome', 'Huarochiri'),
  ('San Damian', 'Huarochiri'),
  ('San Juan de Iris', 'Huarochiri'),
  ('San Juan de Tantaranche', 'Huarochiri'),
  ('San Lorenzo de Quinti', 'Huarochiri'),
  ('San Mateo', 'Huarochiri'),
  ('San Mateo de Otao', 'Huarochiri'),
  ('San Pedro de Casta', 'Huarochiri'),
  ('San Pedro de Huancayre', 'Huarochiri'),
  ('Sangallaya', 'Huarochiri'),
  ('Santa Cruz de Cocachacra', 'Huarochiri'),
  ('Santa Eulalia', 'Huarochiri'),
  ('Santiago de Anchucaya', 'Huarochiri'),
  ('Santiago de Tuna', 'Huarochiri'),
  ('Santo Domingo de los Olleros', 'Huarochiri'),
  ('Surco', 'Huarochiri'),
  ('Ambar', 'Huaura'),
  ('Caleta de Carquin', 'Huaura'),
  ('Checras', 'Huaura'),
  ('Huacho', 'Huaura'),
  ('Hualmay', 'Huaura'),
  ('Huaura', 'Huaura'),
  ('Leoncio Prado', 'Huaura'),
  ('Paccho', 'Huaura'),
  ('Santa Leonor', 'Huaura'),
  ('Santa Maria', 'Huaura'),
  ('Sayan', 'Huaura'),
  ('Vegueta', 'Huaura'),
  ('Caraz', 'Huaylas'),
  ('Huallanca', 'Huaylas'),
  ('Huata', 'Huaylas'),
  ('Huaylas', 'Huaylas'),
  ('Mato', 'Huaylas'),
  ('Pamparomas', 'Huaylas'),
  ('Pueblo Libre', 'Huaylas'),
  ('Santa Cruz', 'Huaylas'),
  ('Santo Toribio', 'Huaylas'),
  ('Yuracmarca', 'Huaylas'),
  ('Ayavi', 'Huaytara'),
  ('Cordova', 'Huaytara'),
  ('Huayacundo Arma', 'Huaytara'),
  ('Huaytara', 'Huaytara'),
  ('Laramarca', 'Huaytara'),
  ('Ocoyo', 'Huaytara'),
  ('Pilpichaca', 'Huaytara'),
  ('Querco', 'Huaytara'),
  ('Quito-Arma', 'Huaytara'),
  ('San Antonio de Cusicancha', 'Huaytara'),
  ('San Francisco de Sangayaico', 'Huaytara'),
  ('San Isidro', 'Huaytara'),
  ('Santiago de Chocorvos', 'Huaytara'),
  ('Santiago de Quirahuara', 'Huaytara'),
  ('Santo Domingo de Capillas', 'Huaytara'),
  ('Tambo', 'Huaytara'),
  ('Ica', 'Ica'),
  ('La Tinguiqa', 'Ica'),
  ('Los Aquijes', 'Ica'),
  ('Ocucaje', 'Ica'),
  ('Pachacutec', 'Ica'),
  ('Parcona', 'Ica'),
  ('Pueblo Nuevo', 'Ica'),
  ('Salas', 'Ica'),
  ('San Jose de los Molinos', 'Ica'),
  ('San Juan Bautista', 'Ica'),
  ('Santiago', 'Ica'),
  ('Subtanjalla', 'Ica'),
  ('Tate', 'Ica'),
  ('Yauca del Rosario  1/', 'Ica'),
  ('El Algarrobal', 'Ilo'),
  ('Ilo', 'Ilo'),
  ('Pacocha', 'Ilo'),
  ('Cocachacra', 'Islay'),
  ('Dean Valdivia', 'Islay'),
  ('Islay', 'Islay'),
  ('Mejia', 'Islay'),
  ('Mollendo', 'Islay'),
  ('Punta de Bombon', 'Islay'),
  ('Bellavista', 'Jaen'),
  ('Chontali', 'Jaen'),
  ('Colasay', 'Jaen'),
  ('Huabal', 'Jaen'),
  ('Jaen', 'Jaen'),
  ('Las Pirias', 'Jaen'),
  ('Pomahuaca', 'Jaen'),
  ('Pucara', 'Jaen'),
  ('Sallique', 'Jaen'),
  ('San Felipe', 'Jaen'),
  ('San Jose del Alto', 'Jaen'),
  ('Santa Rosa', 'Jaen'),
  ('Acolla', 'Jauja'),
  ('Apata', 'Jauja'),
  ('Ataura', 'Jauja'),
  ('Canchayllo', 'Jauja'),
  ('Curicaca', 'Jauja'),
  ('El Mantaro', 'Jauja'),
  ('Huamali', 'Jauja'),
  ('Huaripampa', 'Jauja'),
  ('Huertas', 'Jauja'),
  ('Janjaillo', 'Jauja'),
  ('Jauja', 'Jauja'),
  ('Julcan', 'Jauja'),
  ('Leonor Ordoqez', 'Jauja'),
  ('Llocllapampa', 'Jauja'),
  ('Marco', 'Jauja'),
  ('Masma', 'Jauja'),
  ('Masma Chicche', 'Jauja'),
  ('Molinos', 'Jauja'),
  ('Monobamba', 'Jauja'),
  ('Muqui', 'Jauja'),
  ('Muquiyauyo', 'Jauja'),
  ('Paca', 'Jauja'),
  ('Paccha', 'Jauja'),
  ('Pancan', 'Jauja'),
  ('Parco', 'Jauja'),
  ('Pomacancha', 'Jauja'),
  ('Ricran', 'Jauja'),
  ('San Lorenzo', 'Jauja'),
  ('San Pedro de Chunan', 'Jauja'),
  ('Sausa', 'Jauja'),
  ('Sincos', 'Jauja'),
  ('Tunan Marca', 'Jauja'),
  ('Yauli', 'Jauja'),
  ('Yauyos', 'Jauja'),
  ('Ilabaya', 'Jorge Basadre'),
  ('Ite', 'Jorge Basadre'),
  ('Locumba', 'Jorge Basadre'),
  ('Calamarca', 'Julcan'),
  ('Carabamba', 'Julcan'),
  ('Huaso', 'Julcan'),
  ('Julcan', 'Julcan'),
  ('Carhuamayo', 'Junin'),
  ('Junin', 'Junin'),
  ('Ondores', 'Junin'),
  ('Ulcumayo', 'Junin'),
  ('Echarate', 'La Convencion'),
  ('Huayopata', 'La Convencion'),
  ('Maranura', 'La Convencion'),
  ('Ocobamba', 'La Convencion'),
  ('Pichari', 'La Convencion'),
  ('Quellouno', 'La Convencion'),
  ('Quimbiri', 'La Convencion'),
  ('Santa Ana', 'La Convencion'),
  ('Santa Teresa', 'La Convencion'),
  ('Vilcabamba', 'La Convencion'),
  ('Anco', 'La Mar'),
  ('Ayna', 'La Mar'),
  ('Chilcas', 'La Mar'),
  ('Chungui', 'La Mar'),
  ('Luis Carranza', 'La Mar'),
  ('San Miguel', 'La Mar'),
  ('Santa Rosa', 'La Mar'),
  ('Tambo', 'La Mar'),
  ('Alca', 'La Union'),
  ('Charcana', 'La Union'),
  ('Cotahuasi', 'La Union'),
  ('Huaynacotas', 'La Union'),
  ('Pampamarca', 'La Union'),
  ('Puyca', 'La Union'),
  ('Quechualla', 'La Union'),
  ('Sayla', 'La Union'),
  ('Tauria', 'La Union'),
  ('Tomepampa', 'La Union'),
  ('Toro', 'La Union'),
  ('Alonso de Alvarado', 'Lamas'),
  ('Barranquita', 'Lamas'),
  ('Caynarachi', 'Lamas'),
  ('Cuqumbuqui', 'Lamas'),
  ('Lamas', 'Lamas'),
  ('Pinto Recodo', 'Lamas'),
  ('Rumisapa', 'Lamas'),
  ('San Roque de Cumbaza', 'Lamas'),
  ('Shanao', 'Lamas'),
  ('Tabalosos', 'Lamas'),
  ('Zapatero', 'Lamas'),
  ('Chochope', 'Lambayeque'),
  ('Illimo', 'Lambayeque'),
  ('Jayanca', 'Lambayeque'),
  ('Lambayeque', 'Lambayeque'),
  ('Mochumi', 'Lambayeque'),
  ('Morrope', 'Lambayeque'),
  ('Motupe', 'Lambayeque'),
  ('Olmos', 'Lambayeque'),
  ('Pacora', 'Lambayeque'),
  ('Salas', 'Lambayeque'),
  ('San Jose', 'Lambayeque'),
  ('Tucume', 'Lambayeque'),
  ('Cabanilla', 'Lampa'),
  ('Calapuja', 'Lampa'),
  ('Lampa', 'Lampa'),
  ('Nicasio', 'Lampa'),
  ('Ocuviri', 'Lampa'),
  ('Palca', 'Lampa'),
  ('Paratia', 'Lampa'),
  ('Pucara', 'Lampa'),
  ('Santa Lucia', 'Lampa'),
  ('Vilavila', 'Lampa'),
  ('Baqos', 'Lauricocha'),
  ('Jesus', 'Lauricocha'),
  ('Jivia', 'Lauricocha'),
  ('Queropalca', 'Lauricocha'),
  ('Rondos', 'Lauricocha'),
  ('San Francisco de Asis', 'Lauricocha'),
  ('San Miguel de Cauri', 'Lauricocha'),
  ('Daniel Alomias Robles', 'Leoncio Prado'),
  ('Hermilio Valdizan', 'Leoncio Prado'),
  ('Jose Crespo y Castillo', 'Leoncio Prado'),
  ('Luyando', 'Leoncio Prado'),
  ('Mariano Damaso Beraun', 'Leoncio Prado'),
  ('Rupa-Rupa', 'Leoncio Prado'),
  ('Ancón', 'Lima'),
  ('Ate', 'Lima'),
  ('Barranco', 'Lima'),
  ('Breña', 'Lima'),
  ('Carabayllo', 'Lima'),
  ('Cercado de Lima', 'Lima'),
  ('Chaclacayo', 'Lima'),
  ('Chorrillos', 'Lima'),
  ('Cieneguilla', 'Lima'),
  ('Comas', 'Lima'),
  ('El Agustino', 'Lima'),
  ('Independencia', 'Lima'),
  ('Jesús María', 'Lima'),
  ('La Molina', 'Lima'),
  ('La Victoria', 'Lima'),
  ('Lince', 'Lima'),
  ('Los Olivos', 'Lima'),
  ('Lurigancho', 'Lima'),
  ('Lurín', 'Lima'),
  ('Magdalena del Mar', 'Lima'),
  ('Miraflores', 'Lima'),
  ('Pachacámac', 'Lima'),
  ('Pucusana', 'Lima'),
  ('Pueblo Libre', 'Lima'),
  ('Puente Piedra', 'Lima'),
  ('Punta Hermosa', 'Lima'),
  ('Punta Negra', 'Lima'),
  ('Rímac', 'Lima'),
  ('San Bartolo', 'Lima'),
  ('San Borja', 'Lima'),
  ('San Isidro', 'Lima'),
  ('San Juan de Lurigancho', 'Lima'),
  ('San Juan de Miraflores', 'Lima'),
  ('San Luis', 'Lima'),
  ('San Martín de Porres', 'Lima'),
  ('San Miguel', 'Lima'),
  ('Santa Anita', 'Lima'),
  ('Santa María del Mar', 'Lima'),
  ('Santa Rosa', 'Lima'),
  ('Santiago de Surco', 'Lima'),
  ('Surquillo', 'Lima'),
  ('Villa El Salvador', 'Lima'),
  ('Villa María del Triunfo', 'Lima'),
  ('Nauta', 'Loreto'),
  ('Parinari', 'Loreto'),
  ('Tigre', 'Loreto'),
  ('Trompeteros', 'Loreto'),
  ('Urarinas', 'Loreto'),
  ('Aucara', 'Lucanas'),
  ('Cabana', 'Lucanas'),
  ('Carmen Salcedo', 'Lucanas'),
  ('Chaviqa', 'Lucanas'),
  ('Chipao', 'Lucanas'),
  ('Huac-Huas', 'Lucanas'),
  ('Laramate', 'Lucanas'),
  ('Leoncio Prado', 'Lucanas'),
  ('Llauta', 'Lucanas'),
  ('Lucanas', 'Lucanas'),
  ('Ocaqa', 'Lucanas'),
  ('Otoca', 'Lucanas'),
  ('Puquio', 'Lucanas'),
  ('Saisa', 'Lucanas'),
  ('San Cristobal', 'Lucanas'),
  ('San Juan', 'Lucanas'),
  ('San Pedro', 'Lucanas'),
  ('San Pedro de Palco', 'Lucanas'),
  ('Sancos', 'Lucanas'),
  ('Santa Ana de Huaycahuacho', 'Lucanas'),
  ('Santa Lucia', 'Lucanas'),
  ('Camporredondo', 'Luya'),
  ('Cocabamba', 'Luya'),
  ('Colcamar', 'Luya'),
  ('Conila', 'Luya'),
  ('Inguilpata', 'Luya'),
  ('Lamud', 'Luya'),
  ('Longuita', 'Luya'),
  ('Lonya Chico', 'Luya'),
  ('Luya', 'Luya'),
  ('Luya Viejo', 'Luya'),
  ('Maria', 'Luya'),
  ('Ocalli', 'Luya'),
  ('Ocumal', 'Luya'),
  ('Pisuquia', 'Luya'),
  ('Providencia', 'Luya'),
  ('San Cristobal', 'Luya'),
  ('San Francisco del Yeso', 'Luya'),
  ('San Jeronimo', 'Luya'),
  ('San Juan de Lopecancha', 'Luya'),
  ('Santa Catalina', 'Luya'),
  ('Santo Tomas', 'Luya'),
  ('Tingo', 'Luya'),
  ('Trita', 'Luya'),
  ('Fitzcarrald', 'Manu'),
  ('Huepetuhe', 'Manu'),
  ('Madre de Dios', 'Manu'),
  ('Manu', 'Manu'),
  ('Cholon', 'Maraqon'),
  ('Huacrachuco', 'Maraqon'),
  ('San Buenaventura', 'Maraqon'),
  ('Campanilla', 'Mariscal Caceres'),
  ('Huicungo', 'Mariscal Caceres'),
  ('Juanjui', 'Mariscal Caceres'),
  ('Pachiza', 'Mariscal Caceres'),
  ('Pajarillo', 'Mariscal Caceres'),
  ('Casca', 'Mariscal Luzuriaga'),
  ('Eleazar Guzman Barron', 'Mariscal Luzuriaga'),
  ('Fidel Olivas Escudero', 'Mariscal Luzuriaga'),
  ('Llama', 'Mariscal Luzuriaga'),
  ('Llumpa', 'Mariscal Luzuriaga'),
  ('Lucma', 'Mariscal Luzuriaga'),
  ('Musga', 'Mariscal Luzuriaga'),
  ('Piscobamba', 'Mariscal Luzuriaga'),
  ('Carumas', 'Mariscal Nieto'),
  ('Cuchumbaya', 'Mariscal Nieto'),
  ('Moquegua', 'Mariscal Nieto'),
  ('Samegua', 'Mariscal Nieto'),
  ('San Cristobal', 'Mariscal Nieto'),
  ('Torata', 'Mariscal Nieto'),
  ('Pebas', 'Mariscal Ramon Castilla'),
  ('Ramon Castilla', 'Mariscal Ramon Castilla'),
  ('San Pablo', 'Mariscal Ramon Castilla'),
  ('Yavari', 'Mariscal Ramon Castilla'),
  ('Alto Nanay', 'Maynas'),
  ('Belén', 'Maynas'),
  ('Fernando Lores', 'Maynas'),
  ('Indiana', 'Maynas'),
  ('Iquitos', 'Maynas'),
  ('Las Amazonas', 'Maynas'),
  ('Mazan', 'Maynas'),
  ('Napo', 'Maynas'),
  ('Punchana', 'Maynas'),
  ('Putumayo', 'Maynas'),
  ('San Juan Bautista', 'Maynas'),
  ('Torres Causana', 'Maynas'),
  ('Yaquerana', 'Maynas'),
  ('Antauta', 'Melgar'),
  ('Ayaviri', 'Melgar'),
  ('Cupi', 'Melgar'),
  ('Llalli', 'Melgar'),
  ('Macari', 'Melgar'),
  ('Nuqoa', 'Melgar'),
  ('Orurillo', 'Melgar'),
  ('Santa Rosa', 'Melgar'),
  ('Umachiri', 'Melgar'),
  ('Conima', 'Moho'),
  ('Huayrapata', 'Moho'),
  ('Moho', 'Moho'),
  ('Tilali', 'Moho'),
  ('Buenos Aires', 'Morropon'),
  ('Chalaco', 'Morropon'),
  ('Chulucanas', 'Morropon'),
  ('La Matanza', 'Morropon'),
  ('Morropon', 'Morropon'),
  ('Salitral', 'Morropon'),
  ('San Juan de Bigote', 'Morropon'),
  ('Santa Catalina de Mossa', 'Morropon'),
  ('Santo Domingo', 'Morropon'),
  ('Yamango', 'Morropon'),
  ('Calzada', 'Moyobamba'),
  ('Habana', 'Moyobamba'),
  ('Jepelacio', 'Moyobamba'),
  ('Moyobamba', 'Moyobamba'),
  ('Soritor', 'Moyobamba'),
  ('Yantalo', 'Moyobamba'),
  ('Changuillo', 'Nazca'),
  ('El Ingenio', 'Nazca'),
  ('Marcona', 'Nazca'),
  ('Nazca', 'Nazca'),
  ('Vista Alegre', 'Nazca'),
  ('Acas', 'Ocros'),
  ('Cajamarquilla', 'Ocros'),
  ('Carhuapampa', 'Ocros'),
  ('Cochas', 'Ocros'),
  ('Congas', 'Ocros'),
  ('Llipa', 'Ocros'),
  ('Ocros', 'Ocros'),
  ('San Cristobal de Rajan', 'Ocros'),
  ('San Pedro', 'Ocros'),
  ('Santiago de Chilcas', 'Ocros'),
  ('Agallpampa', 'Otuzco'),
  ('Charat', 'Otuzco'),
  ('Huaranchal', 'Otuzco'),
  ('La Cuesta', 'Otuzco'),
  ('Mache', 'Otuzco'),
  ('Otuzco', 'Otuzco'),
  ('Paranday', 'Otuzco'),
  ('Salpo', 'Otuzco'),
  ('Sinsicap', 'Otuzco'),
  ('Usquil', 'Otuzco'),
  ('Chontabamba', 'Oxapampa'),
  ('Huancabamba', 'Oxapampa'),
  ('Oxapampa', 'Oxapampa'),
  ('Palcazu', 'Oxapampa'),
  ('Pozuzo', 'Oxapampa'),
  ('Puerto Bermudez', 'Oxapampa'),
  ('Villa Rica', 'Oxapampa'),
  ('Andajes', 'Oyon'),
  ('Caujul', 'Oyon'),
  ('Cochamarca', 'Oyon'),
  ('Navan', 'Oyon'),
  ('Oyon', 'Oyon'),
  ('Pachangara', 'Oyon'),
  ('Guadalupe', 'Pacasmayo'),
  ('Jequetepeque', 'Pacasmayo'),
  ('Pacasmayo', 'Pacasmayo'),
  ('San Jose', 'Pacasmayo'),
  ('San Pedro de Lloc', 'Pacasmayo'),
  ('Chaglla', 'Pachitea'),
  ('Molino', 'Pachitea'),
  ('Panao', 'Pachitea'),
  ('Umari', 'Pachitea'),
  ('Curimana', 'Padre Abad'),
  ('Irazola', 'Padre Abad'),
  ('Padre Abad', 'Padre Abad'),
  ('Amotape', 'Paita'),
  ('Arenal', 'Paita'),
  ('Colan', 'Paita'),
  ('La Huaca', 'Paita'),
  ('Paita', 'Paita'),
  ('Tamarindo', 'Paita'),
  ('Vichayal', 'Paita'),
  ('Bolognesi', 'Pallasca'),
  ('Cabana', 'Pallasca'),
  ('Conchucos', 'Pallasca'),
  ('Huacaschuque', 'Pallasca'),
  ('Huandoval', 'Pallasca'),
  ('Lacabamba', 'Pallasca'),
  ('Llapo', 'Pallasca'),
  ('Pallasca', 'Pallasca'),
  ('Pampas', 'Pallasca'),
  ('Santa Rosa', 'Pallasca'),
  ('Tauca', 'Pallasca'),
  ('Llipata', 'Palpa'),
  ('Palpa', 'Palpa'),
  ('Rio Grande', 'Palpa'),
  ('Santa Cruz', 'Palpa'),
  ('Tibillo', 'Palpa'),
  ('Chumpi', 'Parinacochas'),
  ('Coracora', 'Parinacochas'),
  ('Coronel Castaqeda', 'Parinacochas'),
  ('Pacapausa', 'Parinacochas'),
  ('Pullo', 'Parinacochas'),
  ('Puyusca', 'Parinacochas'),
  ('San Francisco de Ravacayco', 'Parinacochas'),
  ('Upahuacho', 'Parinacochas'),
  ('Accha', 'Paruro'),
  ('Ccapi', 'Paruro'),
  ('Colcha', 'Paruro'),
  ('Huanoquite', 'Paruro'),
  ('Omacha', 'Paruro'),
  ('Paccaritambo', 'Paruro'),
  ('Paruro', 'Paruro'),
  ('Pillpinto', 'Paruro'),
  ('Yaurisque', 'Paruro'),
  ('Chaupimarca', 'Pasco'),
  ('Huachon', 'Pasco'),
  ('Huariaca', 'Pasco'),
  ('Huayllay', 'Pasco'),
  ('Ninacaca', 'Pasco'),
  ('Pallanchacra', 'Pasco'),
  ('Paucartambo', 'Pasco'),
  ('San Fco.De Asis de Yarusyacan', 'Pasco'),
  ('Simon Bolivar', 'Pasco'),
  ('Ticlacayan', 'Pasco'),
  ('Tinyahuarco', 'Pasco'),
  ('Vicco', 'Pasco'),
  ('Yanacancha', 'Pasco'),
  ('Buldibuyo', 'Pataz'),
  ('Chillia', 'Pataz'),
  ('Huancaspata', 'Pataz'),
  ('Huaylillas', 'Pataz'),
  ('Huayo', 'Pataz'),
  ('Ongon', 'Pataz'),
  ('Parcoy', 'Pataz'),
  ('Pataz', 'Pataz'),
  ('Pias', 'Pataz'),
  ('Santiago de Challas', 'Pataz'),
  ('Taurija', 'Pataz'),
  ('Tayabamba', 'Pataz'),
  ('Urpay', 'Pataz'),
  ('Colta', 'Paucar del Sara Sara'),
  ('Corculla', 'Paucar del Sara Sara'),
  ('Lampa', 'Paucar del Sara Sara'),
  ('Marcabamba', 'Paucar del Sara Sara'),
  ('Oyolo', 'Paucar del Sara Sara'),
  ('Pararca', 'Paucar del Sara Sara'),
  ('Pausa', 'Paucar del Sara Sara'),
  ('San Javier de Alpabamba', 'Paucar del Sara Sara'),
  ('San Jose de Ushua', 'Paucar del Sara Sara'),
  ('Sara Sara', 'Paucar del Sara Sara'),
  ('Caicay', 'Paucartambo'),
  ('Challabamba', 'Paucartambo'),
  ('Colquepata', 'Paucartambo'),
  ('Huancarani', 'Paucartambo'),
  ('Kosqipata', 'Paucartambo'),
  ('Paucartambo', 'Paucartambo'),
  ('Buenos Aires', 'Picota'),
  ('Caspisapa', 'Picota'),
  ('Picota', 'Picota'),
  ('Pilluana', 'Picota'),
  ('Pucacaca', 'Picota'),
  ('San Cristobal', 'Picota'),
  ('San Hilarion', 'Picota'),
  ('Shamboyacu', 'Picota'),
  ('Tingo de Ponasa', 'Picota'),
  ('Tres Unidos', 'Picota'),
  ('Huancano', 'Pisco'),
  ('Humay', 'Pisco'),
  ('Independencia', 'Pisco'),
  ('Paracas', 'Pisco'),
  ('Pisco', 'Pisco'),
  ('San Andres', 'Pisco'),
  ('San Clemente', 'Pisco'),
  ('Tupac Amaru Inca', 'Pisco'),
  ('Castilla', 'Piura'),
  ('Catacaos', 'Piura'),
  ('Cura Mori', 'Piura'),
  ('El Tallán', 'Piura'),
  ('La Arena', 'Piura'),
  ('La Unión', 'Piura'),
  ('Las Lomas', 'Piura'),
  ('Piura', 'Piura'),
  ('Tambo Grande', 'Piura'),
  ('Huayllan', 'Pomabamba'),
  ('Parobamba', 'Pomabamba'),
  ('Pomabamba', 'Pomabamba'),
  ('Quinuabamba', 'Pomabamba'),
  ('Codo del Pozuzo', 'Puerto Inca'),
  ('Honoria', 'Puerto Inca'),
  ('Puerto Inca', 'Puerto Inca'),
  ('Tournavista', 'Puerto Inca'),
  ('Yuyapichis', 'Puerto Inca'),
  ('Acora', 'Puno'),
  ('Amantani', 'Puno'),
  ('Atuncolla', 'Puno'),
  ('Capachica', 'Puno'),
  ('Chucuito', 'Puno'),
  ('Coata', 'Puno'),
  ('Huata', 'Puno'),
  ('Maqazo', 'Puno'),
  ('Paucarcolla', 'Puno'),
  ('Pichacani', 'Puno'),
  ('Plateria', 'Puno'),
  ('Puno', 'Puno'),
  ('San Antonio', 'Puno'),
  ('Tiquillaca', 'Puno'),
  ('Vilque', 'Puno'),
  ('Purus', 'Purus'),
  ('Andahuaylillas', 'Quispicanchi'),
  ('Camanti', 'Quispicanchi'),
  ('Ccarhuayo', 'Quispicanchi'),
  ('Ccatca', 'Quispicanchi'),
  ('Cusipata', 'Quispicanchi'),
  ('Huaro', 'Quispicanchi'),
  ('Lucre', 'Quispicanchi'),
  ('Marcapata', 'Quispicanchi'),
  ('Ocongate', 'Quispicanchi'),
  ('Oropesa', 'Quispicanchi'),
  ('Quiquijana', 'Quispicanchi'),
  ('Urcos', 'Quispicanchi'),
  ('Catac', 'Recuay'),
  ('Cotaparaco', 'Recuay'),
  ('Huayllapampa', 'Recuay'),
  ('Llacllin', 'Recuay'),
  ('Marca', 'Recuay'),
  ('Pampas Chico', 'Recuay'),
  ('Pararin', 'Recuay'),
  ('Recuay', 'Recuay'),
  ('Tapacocha', 'Recuay'),
  ('Ticapampa', 'Recuay'),
  ('Alto Tapiche', 'Requena'),
  ('Capelo', 'Requena'),
  ('Emilio San Martin', 'Requena'),
  ('Jenaro Herrera', 'Requena'),
  ('Maquia', 'Requena'),
  ('Puinahua', 'Requena'),
  ('Requena', 'Requena'),
  ('Saquena', 'Requena'),
  ('Soplin', 'Requena'),
  ('Tapiche', 'Requena'),
  ('Yaquerana', 'Requena'),
  ('Awajun', 'Rioja'),
  ('Elias Soplin Vargas', 'Rioja'),
  ('Nueva Cajamarca', 'Rioja'),
  ('Pardo Miguel', 'Rioja'),
  ('Posic', 'Rioja'),
  ('Rioja', 'Rioja'),
  ('San Fernando', 'Rioja'),
  ('Yorongos', 'Rioja'),
  ('Yuracyacu', 'Rioja'),
  ('Chirimoto', 'Rodriguez de Mendoza'),
  ('Cochamal', 'Rodriguez de Mendoza'),
  ('Huambo', 'Rodriguez de Mendoza'),
  ('Limabamba', 'Rodriguez de Mendoza'),
  ('Longar', 'Rodriguez de Mendoza'),
  ('Mariscal Benavides', 'Rodriguez de Mendoza'),
  ('Milpuc', 'Rodriguez de Mendoza'),
  ('Omia', 'Rodriguez de Mendoza'),
  ('San Nicolas', 'Rodriguez de Mendoza'),
  ('Santa Rosa', 'Rodriguez de Mendoza'),
  ('Totora', 'Rodriguez de Mendoza'),
  ('Vista Alegre', 'Rodriguez de Mendoza'),
  ('Ananea', 'San Antonio de Putina'),
  ('Pedro Vilca Apaza', 'San Antonio de Putina'),
  ('Putina', 'San Antonio de Putina'),
  ('Quilcapuncu', 'San Antonio de Putina'),
  ('Sina', 'San Antonio de Putina'),
  ('Chirinos', 'San Ignacio'),
  ('Huarango', 'San Ignacio'),
  ('La Coipa', 'San Ignacio'),
  ('Namballe', 'San Ignacio'),
  ('San Ignacio', 'San Ignacio'),
  ('San Jose de Lourdes', 'San Ignacio'),
  ('Tabaconas', 'San Ignacio'),
  ('Chancay', 'San Marcos'),
  ('Eduardo Villanueva', 'San Marcos'),
  ('Gregorio Pita', 'San Marcos'),
  ('Ichocan', 'San Marcos'),
  ('Jose Manuel Quiroz', 'San Marcos'),
  ('Jose Sabogal', 'San Marcos'),
  ('Pedro Galvez', 'San Marcos'),
  ('Alberto Leveau', 'San Martin'),
  ('Cacatachi', 'San Martin'),
  ('Chazuta', 'San Martin'),
  ('Chipurana', 'San Martin'),
  ('El Porvenir', 'San Martin'),
  ('Huimbayoc', 'San Martin'),
  ('Juan Guerra', 'San Martin'),
  ('La Banda de Shilcayo', 'San Martin'),
  ('Morales', 'San Martin'),
  ('Papaplaya', 'San Martin'),
  ('San Antonio', 'San Martin'),
  ('Sauce', 'San Martin'),
  ('Shapaja', 'San Martin'),
  ('Tarapoto', 'San Martin'),
  ('Bolivar', 'San Miguel'),
  ('Calquis', 'San Miguel'),
  ('Catilluc', 'San Miguel'),
  ('El Prado', 'San Miguel'),
  ('La Florida', 'San Miguel'),
  ('Llapa', 'San Miguel'),
  ('Nanchoc', 'San Miguel'),
  ('Niepos', 'San Miguel'),
  ('San Gregorio', 'San Miguel'),
  ('San Miguel', 'San Miguel'),
  ('San Silvestre de Cochan', 'San Miguel'),
  ('Tongod', 'San Miguel'),
  ('Union Agua Blanca', 'San Miguel'),
  ('San Bernardino', 'San Pablo'),
  ('San Luis', 'San Pablo'),
  ('San Pablo', 'San Pablo'),
  ('Tumbaden', 'San Pablo'),
  ('Cabana', 'San Roman'),
  ('Cabanillas', 'San Roman'),
  ('Caracoto', 'San Roman'),
  ('Juliaca', 'San Roman'),
  ('Chugay', 'Sanchez Carrion'),
  ('Cochorco', 'Sanchez Carrion'),
  ('Curgos', 'Sanchez Carrion'),
  ('Huamachuco', 'Sanchez Carrion'),
  ('Marcabal', 'Sanchez Carrion'),
  ('Sanagoran', 'Sanchez Carrion'),
  ('Sarin', 'Sanchez Carrion'),
  ('Sartimbamba', 'Sanchez Carrion'),
  ('Alto Inambari', 'Sandia'),
  ('Cuyocuyo', 'Sandia'),
  ('Limbani', 'Sandia'),
  ('Patambuco', 'Sandia'),
  ('Phara', 'Sandia'),
  ('Quiaca', 'Sandia'),
  ('San Juan del Oro', 'Sandia'),
  ('Sandia', 'Sandia'),
  ('Yanahuaya', 'Sandia'),
  ('Caceres del Peru', 'Santa'),
  ('Chimbote', 'Santa'),
  ('Coishco', 'Santa'),
  ('Macate', 'Santa'),
  ('Moro', 'Santa'),
  ('Nepeqa', 'Santa'),
  ('Nuevo Chimbote', 'Santa'),
  ('Samanco', 'Santa'),
  ('Santa', 'Santa'),
  ('Andabamba', 'Santa Cruz'),
  ('Catache', 'Santa Cruz'),
  ('Chancaybaqos', 'Santa Cruz'),
  ('La Esperanza', 'Santa Cruz'),
  ('Ninabamba', 'Santa Cruz'),
  ('Pulan', 'Santa Cruz'),
  ('Santa Cruz', 'Santa Cruz'),
  ('Saucepampa', 'Santa Cruz'),
  ('Sexi', 'Santa Cruz'),
  ('Uticyacu', 'Santa Cruz'),
  ('Yauyucan', 'Santa Cruz'),
  ('Angasmarca', 'Santiago de Chuco'),
  ('Cachicadan', 'Santiago de Chuco'),
  ('Mollebamba', 'Santiago de Chuco'),
  ('Mollepata', 'Santiago de Chuco'),
  ('Quiruvilca', 'Santiago de Chuco'),
  ('Santa Cruz de Chuca', 'Santiago de Chuco'),
  ('Santiago de Chuco', 'Santiago de Chuco'),
  ('Sitabamba', 'Santiago de Chuco'),
  ('Coviriali', 'Satipo'),
  ('Llaylla', 'Satipo'),
  ('Mazamari', 'Satipo'),
  ('Pampa Hermosa', 'Satipo'),
  ('Pangoa', 'Satipo'),
  ('Rio Negro', 'Satipo'),
  ('Rio Tambo', 'Satipo'),
  ('Satipo', 'Satipo'),
  ('Bellavista de la Union', 'Sechura'),
  ('Bernal', 'Sechura'),
  ('Cristo Nos Valga', 'Sechura'),
  ('Rinconada Llicuar', 'Sechura'),
  ('Sechura', 'Sechura'),
  ('Vice', 'Sechura'),
  ('Acobamba', 'Sihuas'),
  ('Alfonso Ugarte', 'Sihuas'),
  ('Cashapampa', 'Sihuas'),
  ('Chingalpo', 'Sihuas'),
  ('Huayllabamba', 'Sihuas'),
  ('Quiches', 'Sihuas'),
  ('Ragash', 'Sihuas'),
  ('San Juan', 'Sihuas'),
  ('Sicsibamba', 'Sihuas'),
  ('Sihuas', 'Sihuas'),
  ('Belen', 'Sucre'),
  ('Chalcos', 'Sucre'),
  ('Chilcayoc', 'Sucre'),
  ('Huacaqa', 'Sucre'),
  ('Morcolla', 'Sucre'),
  ('Paico', 'Sucre'),
  ('Querobamba', 'Sucre'),
  ('San Pedro de Larcay', 'Sucre'),
  ('San Salvador de Quije', 'Sucre'),
  ('Santiago de Paucaray', 'Sucre'),
  ('Soras', 'Sucre'),
  ('Bellavista', 'Sullana'),
  ('Ignacio Escudero', 'Sullana'),
  ('Lancones', 'Sullana'),
  ('Marcavelica', 'Sullana'),
  ('Miguel Checa', 'Sullana'),
  ('Querecotillo', 'Sullana'),
  ('Salitral', 'Sullana'),
  ('Sullana', 'Sullana'),
  ('Alto de la Alianza', 'Tacna'),
  ('Calana', 'Tacna'),
  ('Ciudad Nueva', 'Tacna'),
  ('Cor Gregorio Albarracín', 'Tacna'),
  ('Inclan', 'Tacna'),
  ('Pachia', 'Tacna'),
  ('Palca', 'Tacna'),
  ('Pocollay', 'Tacna'),
  ('Sama', 'Tacna'),
  ('Tacna', 'Tacna'),
  ('Iberia', 'Tahuamanu'),
  ('Iqapari', 'Tahuamanu'),
  ('Tahuamanu', 'Tahuamanu'),
  ('El Alto', 'Talara'),
  ('La Brea', 'Talara'),
  ('Lobitos', 'Talara'),
  ('Los Organos', 'Talara'),
  ('Mancora', 'Talara'),
  ('Pariqas', 'Talara'),
  ('Inambari', 'Tambopata'),
  ('Laberinto', 'Tambopata'),
  ('Las Piedras', 'Tambopata'),
  ('Tambopata', 'Tambopata'),
  ('Chucatamani', 'Tarata'),
  ('Estique', 'Tarata'),
  ('Estique-Pampa', 'Tarata'),
  ('Sitajara', 'Tarata'),
  ('Susapaya', 'Tarata'),
  ('Tarata', 'Tarata'),
  ('Tarucachi', 'Tarata'),
  ('Ticaco', 'Tarata'),
  ('Acobamba', 'Tarma'),
  ('Huaricolca', 'Tarma'),
  ('Huasahuasi', 'Tarma'),
  ('La Union', 'Tarma'),
  ('Palca', 'Tarma'),
  ('Palcamayo', 'Tarma'),
  ('San Pedro de Cajas', 'Tarma'),
  ('Tapo', 'Tarma'),
  ('Tarma', 'Tarma'),
  ('Acostambo', 'Tayacaja'),
  ('Acraquia', 'Tayacaja'),
  ('Ahuaycha', 'Tayacaja'),
  ('Colcabamba', 'Tayacaja'),
  ('Daniel Hernandez', 'Tayacaja'),
  ('Huachocolpa', 'Tayacaja'),
  ('Huando', 'Tayacaja'),
  ('Huaribamba', 'Tayacaja'),
  ('Pachamarca', 'Tayacaja'),
  ('Pampas', 'Tayacaja'),
  ('Pazos', 'Tayacaja'),
  ('Qahuimpuquio', 'Tayacaja'),
  ('Quishuar', 'Tayacaja'),
  ('Salcabamba', 'Tayacaja'),
  ('Salcahuasi', 'Tayacaja'),
  ('San Marcos de Rocchac', 'Tayacaja'),
  ('Surcubamba', 'Tayacaja'),
  ('Tintay Puncu', 'Tayacaja'),
  ('Nuevo Progreso', 'Tocache'),
  ('Polvora', 'Tocache'),
  ('Shunte', 'Tocache'),
  ('Tocache', 'Tocache'),
  ('Uchiza', 'Tocache'),
  ('El Porvenir', 'Trujillo'),
  ('Florencia de Mora', 'Trujillo'),
  ('Huanchaco', 'Trujillo'),
  ('La Esperanza', 'Trujillo'),
  ('Laredo', 'Trujillo'),
  ('Moche', 'Trujillo'),
  ('Poroto', 'Trujillo'),
  ('Salaverry', 'Trujillo'),
  ('Simbal', 'Trujillo'),
  ('Trujillo', 'Trujillo'),
  ('Víctor Larco Herrera', 'Trujillo'),
  ('Corrales', 'Tumbes'),
  ('La Cruz', 'Tumbes'),
  ('Pampas de Hospital', 'Tumbes'),
  ('San Jacinto', 'Tumbes'),
  ('San Juan de la Virgen', 'Tumbes'),
  ('Tumbes', 'Tumbes'),
  ('Contamana', 'Ucayali'),
  ('Inahuaya', 'Ucayali'),
  ('Padre Marquez', 'Ucayali'),
  ('Pampa Hermosa', 'Ucayali'),
  ('Sarayacu', 'Ucayali'),
  ('Vargas Guerra', 'Ucayali'),
  ('Chinchero', 'Urubamba'),
  ('Huayllabamba', 'Urubamba'),
  ('Machupicchu', 'Urubamba'),
  ('Maras', 'Urubamba'),
  ('Ollantaytambo', 'Urubamba'),
  ('Urubamba', 'Urubamba'),
  ('Yucay', 'Urubamba'),
  ('Bagua Grande', 'Utcubamba'),
  ('Cajaruro', 'Utcubamba'),
  ('Cumba', 'Utcubamba'),
  ('El Milagro', 'Utcubamba'),
  ('Jamalca', 'Utcubamba'),
  ('Lonya Grande', 'Utcubamba'),
  ('Yamon', 'Utcubamba'),
  ('Alcamenca', 'Victor Fajardo'),
  ('Apongo', 'Victor Fajardo'),
  ('Asquipata', 'Victor Fajardo'),
  ('Canaria', 'Victor Fajardo'),
  ('Cayara', 'Victor Fajardo'),
  ('Colca', 'Victor Fajardo'),
  ('Huamanquiquia', 'Victor Fajardo'),
  ('Huancapi', 'Victor Fajardo'),
  ('Huancaraylla', 'Victor Fajardo'),
  ('Huaya', 'Victor Fajardo'),
  ('Sarhua', 'Victor Fajardo'),
  ('Vilcanchos', 'Victor Fajardo'),
  ('Accomarca', 'Vilcas Huaman'),
  ('Carhuanca', 'Vilcas Huaman'),
  ('Concepcion', 'Vilcas Huaman'),
  ('Huambalpa', 'Vilcas Huaman'),
  ('Independencia', 'Vilcas Huaman'),
  ('Saurama', 'Vilcas Huaman'),
  ('Vilcas Huaman', 'Vilcas Huaman'),
  ('Vischongo', 'Vilcas Huaman'),
  ('Chao', 'Viru'),
  ('Guadalupito', 'Viru'),
  ('Viru', 'Viru'),
  ('Cahuac', 'Yarowilca'),
  ('Chacabamba', 'Yarowilca'),
  ('Chavinillo', 'Yarowilca'),
  ('Choras', 'Yarowilca'),
  ('Chupan', 'Yarowilca'),
  ('Jacas Chico', 'Yarowilca'),
  ('Obas', 'Yarowilca'),
  ('Pampamarca', 'Yarowilca'),
  ('Chacapalpa', 'Yauli'),
  ('Huay-Huay', 'Yauli'),
  ('La Oroya', 'Yauli'),
  ('Marcapomacocha', 'Yauli'),
  ('Morococha', 'Yauli'),
  ('Paccha', 'Yauli'),
  ('Santa Barbara de Carhuacayan', 'Yauli'),
  ('Santa Rosa de Sacco', 'Yauli'),
  ('Suitucancha', 'Yauli'),
  ('Yauli', 'Yauli'),
  ('Alis', 'Yauyos'),
  ('Ayauca', 'Yauyos'),
  ('Ayaviri', 'Yauyos'),
  ('Azangaro', 'Yauyos'),
  ('Cacra', 'Yauyos'),
  ('Carania', 'Yauyos'),
  ('Catahuasi', 'Yauyos'),
  ('Chocos', 'Yauyos'),
  ('Cochas', 'Yauyos'),
  ('Colonia', 'Yauyos'),
  ('Hongos', 'Yauyos'),
  ('Huampara', 'Yauyos'),
  ('Huancaya', 'Yauyos'),
  ('Huangascar', 'Yauyos'),
  ('Huantan', 'Yauyos'),
  ('Huaqec', 'Yauyos'),
  ('Laraos', 'Yauyos'),
  ('Lincha', 'Yauyos'),
  ('Madean', 'Yauyos'),
  ('Miraflores', 'Yauyos'),
  ('Omas', 'Yauyos'),
  ('Putinza', 'Yauyos'),
  ('Quinches', 'Yauyos'),
  ('Quinocay', 'Yauyos'),
  ('San Joaquin', 'Yauyos'),
  ('San Pedro de Pilas', 'Yauyos'),
  ('Tanta', 'Yauyos'),
  ('Tauripampa', 'Yauyos'),
  ('Tomas', 'Yauyos'),
  ('Tupe', 'Yauyos'),
  ('Viqac', 'Yauyos'),
  ('Vitis', 'Yauyos'),
  ('Yauyos', 'Yauyos'),
  ('Cascapara', 'Yungay'),
  ('Mancos', 'Yungay'),
  ('Matacoto', 'Yungay'),
  ('Quillo', 'Yungay'),
  ('Ranrahirca', 'Yungay'),
  ('Shupluy', 'Yungay'),
  ('Yanama', 'Yungay'),
  ('Yungay', 'Yungay'),
  ('Anapia', 'Yunguyo'),
  ('Copani', 'Yunguyo'),
  ('Cuturapi', 'Yunguyo'),
  ('Ollaraya', 'Yunguyo'),
  ('Tinicachi', 'Yunguyo'),
  ('Unicachi', 'Yunguyo'),
  ('Yunguyo', 'Yunguyo'),
  ('Aguas Verdes', 'Zarumilla'),
  ('Matapalo', 'Zarumilla'),
  ('Papayal', 'Zarumilla'),
  ('Zarumilla', 'Zarumilla')
ON CONFLICT (name, city) DO NOTHING;
